version: '2'
services:
    jila-backend:
        build: ruby
        restart: unless-stopped
        volumes:
        # code
        - ~/src/jila-backend/:/opt/jila/
        ports:
        - 3000:3000
        command: bundle exec unicorn -p 3000 -c ./config/unicorn.rb
        links:
        - postgres
    postgres:
        image: postgres:9.6.1
        ports:
          - "5432"
